### ISSUE TITLE
MirkoPC_V1_3D_model_2021-03-16.pdf damaged/wrong content?

### ISSUE THREAD

**Issue by TMillesich** [mfolejewski/MirkoPC#2]
The file: 
MirkoPC_V1_3D_model_2021-03-16.pdf 11MB

shows only a white rectangle.
Even at 1000% no further details visible.

PDF Informations:
Paper Dimension: 2,97 x 2,09 cm

**Comment by mfolejewski** [comment]
Github issue.
Please download this file and use Adobe Acrobat to open it.

![obraz](https://user-images.githubusercontent.com/58222533/114293505-e43e6b80-9a96-11eb-96c8-7b942e515d71.png)

**Comment by mfolejewski** [comment]
I checked the PDF file on the github, is OK.
If you have an issue opening this file -> just download this PDF file and use free Adobe Acrobat Viewer.
Another option - please download the STEP 3D file and use any 3D CAD tool, e.g. FreeCAD, Inventor, Fusion 360.
