### ISSUE TITLE
USB power

### ISSUE THREAD

**Issue by Julspower** [mfolejewski/MirkoPC#7]
Hi
I did try your board for the first time today (finally)
programmed the emmc using windows 10 work great
connect a lcd
switch to OS, boot
I get to the raspberry os
connect my K400 unify dongle to usb
no keyboard or mouse
reboot with dongle connected no keyboard or mouse
plug a usb flash no led on the drive

it seem like my usb hub doesn't power the usb connector
is there something I have to do to enable it?

**Comment by Julspower** [comment]
C250 has 4.89V 
but pin 3 of U250 is at 0V
when the power is removed I mesure around 540ohm at C251 which might be U250 but im not sure

**Comment by Julspower** [comment]
Pin 4 of U250 is at 2.8V seem this pin is left floating, its an open drain so U250 is not reporting fault
but I think this pin need a pullup (might be internal to the other end of that trace, I haven't checked)

**Comment by mfolejewski** [comment]
> Hi I did try your board for the first time today (finally) programmed the emmc using windows 10 work great connect a lcd switch to OS, boot I get to the raspberry os connect my K400 unify dongle to usb no keyboard or mouse reboot with dongle connected no keyboard or mouse plug a usb flash no led on the drive
> 
> it seem like my usb hub doesn't power the usb connector is there something I have to do to enable it?

This is the most popular CM4 issue with the USB interface:

See the CM4 datasheet:

The USB interface is disabled to save power by default on the CM4 . To enable it you need to add
dtoverlay=dwc2,dr_mode=host to the config.txt file

https://www.jeffgeerling.com/blog/2020/usb-20-ports-not-working-on-compute-module-4-check-your-overlays

Explanation:
https://github.com/raspberrypi/firmware/issues/1500

**Comment by mfolejewski** [comment]
> C250 has 4.89V and 3.294V on C263 but pin 3 of U250 is at 0V when the power is removed I mesure around 540ohm at C251 which might be U250 but im not sure

Please configure the USB interface at 'config.txt' file:
dtoverlay=dwc2,dr_mode=host
